name: Test Frontend

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install dependencies and run tests
      - name: Set up Node.js (for frontend) 
        uses: actions/setup-node@v2  
        with:
          node-version: '20' 

      - name: Install Dependencies
        run: |
          npm install 

      - name: Run Tests
        run: |
          npm run test  
